hash-format = "sha256"

[[files]]
file = "CREDITS.md"

[[files]]
file = "LICENSE"

[[files]]
file = "config/defaultoptions-common.toml"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/fancytoasts/general.json"

[[files]]
file = "config/fancytoasts/toast.json"

[[files]]
file = "config/fancytoasts/toast_filtering.json"

[[files]]
file = "config/modpack_defaults/config/advancements_reloaded.json"

[[files]]
file = "config/modpack_defaults/config/appleskin.json5"

[[files]]
file = "config/modpack_defaults/config/betterf3.json"

[[files]]
file = "config/modpack_defaults/config/bundles_beyond.json"

[[files]]
file = "config/modpack_defaults/config/chat_heads.json5"

[[files]]
file = "config/modpack_defaults/config/debugify.json"

[[files]]
file = "config/modpack_defaults/config/dynamic_fps.json"

[[files]]
file = "config/modpack_defaults/config/itemscroller.json"

[[files]]
file = "config/modpack_defaults/config/lambdabettergrass.toml"

[[files]]
file = "config/modpack_defaults/config/litematica.json"

[[files]]
file = "config/modpack_defaults/config/locator-heads.json"

[[files]]
file = "config/modpack_defaults/config/locator_lodestones.json"

[[files]]
file = "config/modpack_defaults/config/malilib.json"

[[files]]
file = "config/modpack_defaults/config/minihud.json"

[[files]]
file = "config/modpack_defaults/config/modmenu.json"

[[files]]
file = "config/modpack_defaults/config/particlerain/config.json"

[[files]]
file = "config/modpack_defaults/config/particletweaks.json5"

[[files]]
file = "config/modpack_defaults/config/pingwheel.json"

[[files]]
file = "config/modpack_defaults/config/scribble.client.json"

[[files]]
file = "config/modpack_defaults/config/shulkerboxtooltip.json5"

[[files]]
file = "config/modpack_defaults/config/sodium-extra-options.json"

[[files]]
file = "config/modpack_defaults/config/sodium-options.json"

[[files]]
file = "config/modpack_defaults/config/sodium-shadowy-path-blocks-options.json"

[[files]]
file = "config/modpack_defaults/config/techutils.json"

[[files]]
file = "config/modpack_defaults/config/tweakermore.json"

[[files]]
file = "config/modpack_defaults/config/tweakeroo.json"

[[files]]
file = "config/modpack_defaults/config/xaero/lib/client.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/lib/common.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/lib/profiles/default.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/lib/server_profiles/default.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/client.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/common.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/default_radar_categories_client.json"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/default_radar_categories_server.json"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/profiles/default.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/profiles/entity_radar_categories/default.cfg.json"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/profiles/info_display_config/default.cfg.txt"

[[files]]
file = "config/modpack_defaults/config/xaero/minimap/server_profiles/default.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/world-map/client.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/world-map/common.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/world-map/profiles/default.cfg"

[[files]]
file = "config/modpack_defaults/config/xaero/world-map/server_profiles/default.cfg"

[[files]]
file = "config/modpack_defaults/config/xaerohud.txt"

[[files]]
file = "config/modpack_defaults/customfov.txt"

[[files]]
file = "config/modpack_defaults/resourcepacks/Icons v.1.13.2.zip.rpo"

[[files]]
file = "config/modpack_defaults/resourcepacks/§8§lDarkmode §f§lColourful Containers§8.zip.rpo"

[[files]]
file = "config/modpack_defaults/resourcepacks/§lColourful Containers§8.zip.rpo"

[[files]]
file = "config/modpack_defaults/shaderpacks/I Like Vanilla v1.3.1.zip.txt"

[[files]]
file = "config/modpack_defaults/structurify.json"

[[files]]
file = "config/modpack_defaults/tectonic.json"

[[files]]
file = "config/resourcepackoverrides.json"

[[files]]
file = "config/simpleupdatechecker_modpack.json"

[[files]]
file = "datapacks/name-formatting-station-datapack.pw.toml"
metafile = true

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/advancements-reloaded.pw.toml"
metafile = true

[[files]]
file = "mods/amplified-nether-height.pw.toml"
metafile = true

[[files]]
file = "mods/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/areas.pw.toml"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-extra-extras.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/configmanager.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
metafile = true

[[files]]
file = "mods/custom-fov-illusive.pw.toml"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
metafile = true

[[files]]
file = "mods/deadly-deadly-dungeon.pw.toml"
metafile = true

[[files]]
file = "mods/death-backup.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/disconnect-packet-fix.pw.toml"
metafile = true

[[files]]
file = "mods/dnt-stronghold-overhaul-lite-edition.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-desert-temple-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-jungle-temple-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ocean-monument-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-pillager-outpost-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-swamp-hut-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-woodland-mansion-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/essentialaddons.pw.toml"
metafile = true

[[files]]
file = "mods/essentialclient.pw.toml"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fancy-toasts.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/flashback.pw.toml"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
metafile = true

[[files]]
file = "mods/goats-tool-trims.pw.toml"
metafile = true

[[files]]
file = "mods/herenthere.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/improved-village-placement.pw.toml"
metafile = true

[[files]]
file = "mods/inhabitor.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
metafile = true

[[files]]
file = "mods/locator_lodestones.pw.toml"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
metafile = true

[[files]]
file = "mods/map-distance-fix.pw.toml"
metafile = true

[[files]]
file = "mods/maplink.pw.toml"
metafile = true

[[files]]
file = "mods/mc-258859.pw.toml"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace-reloaded.pw.toml"
metafile = true

[[files]]
file = "mods/model-browser.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/pl3xmap.pw.toml"
metafile = true

[[files]]
file = "mods/pl3xmarkers.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
metafile = true

[[files]]
file = "mods/rail-placement-fix.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/replanting-crops.pw.toml"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
metafile = true

[[files]]
file = "mods/scaffolding-drops-nearby.pw.toml"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/server-replay.pw.toml"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
metafile = true

[[files]]
file = "mods/sha1runtime.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-update-checker.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/smoothtexturefix.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sort-it-out.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/structurify.pw.toml"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
metafile = true

[[files]]
file = "mods/techutils.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terralith-biome-saplings.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
metafile = true

[[files]]
file = "mods/tightfire.pw.toml"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-global-spectator-chat.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
metafile = true

[[files]]
file = "mods/vtdownloader.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
metafile = true

[[files]]
file = "mods/zannaghs-armor-hider.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/VanillaTweaks_3D_MC1.21.x.zip"

[[files]]
file = "resourcepacks/VanillaTweaks_Default_MC1.21.x.zip"

[[files]]
file = "resourcepacks/VanillaTweaks_OreBorders_MC1.21.x.zip"

[[files]]
file = "resourcepacks/chat+.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/colourful-containers-dark-mode-gui.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/colourful-containers-gui.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fa-player-extension.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-creepers.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-details.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-emissive.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-quivers.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/icons.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/i-like-vanilla.pw.toml"
metafile = true
