name = "TerraNugget SMP"
author = "ChrizziNugGet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "355526ddd47ca4948fa0aa4c479af721322f932ed74c1ea11d253d0b6b510c38"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
